server:
    port: 8080

spring:
  config:
    import:
      - classpath:configuration/Swagger.properties
      - classpath:configuration/Database.properties
      - classpath:configuration/Security.properties
      - classpath:configuration/Mail.properties
      - classpath:configuration/Cache.properties
      - classpath:configuration/Storage.properties
      - classpath:configuration/AiClient.properties
      - classpath:prompts/ExerciseHintPrompt.yml
      - classpath:prompts/ChatBotPrompt.yml
      - classpath:prompts/AiGrader.yml
      - classpath:prompts/QuestionConfusion.yml
      - classpath:prompts/LectureConfusion.yml
      

logging:
  level:
    com:
      hcmus:
        mela=debug:


