name: Build and deploy to Prod

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  deploy:
    needs: promote-image
    uses: ./.github/workflows/deploy.yml
    with:
      image_name: ${{ needs.promote-image.outputs.image }}
      environment: prod
    secrets: inherit
