name: prod.yml
on:
  push:
    branches:
      - main

jobs:
  build-image:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build-image
    uses: ./.github/workflows/deploy.yml
    with:
      image_name: ${{ needs.build-image.outputs.image }}
    secrets: inherit
