name: Build and deploy to Prod

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  extract-image-name:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.extract.outputs.image }}
    steps:
      - name: Extract short SHA
        id: short-sha
        run: echo "short-sha=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"

      - name: Extract Image Name
        id: extract
        run: echo "image=ghcr.io/${{ github.repository }}:${{ steps.short-sha.outputs.short-sha }}" >> $GITHUB_OUTPUT

  promote-image:
    needs: extract-image-name
    uses: ./.github/workflows/promote-image.yml
    with:
      image_name: ${{ needs.extract-image-name.outputs.image }}
      new_tag: ${{ github.ref_name }}

  tag-release:
    runs-on: ubuntu-latest
    needs: promote-image
    steps:
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create Git Tag
        run: |
          VERSION=${GITHUB_REF_NAME#release/}
          git tag $VERSION ${{ github.sha }}
          git push origin $VERSION

  deploy:
    needs: promote-image
    uses: ./.github/workflows/deploy.yml
    with:
      image_name: ${{ needs.promote-image.outputs.image }}
      environment: prod
    secrets: inherit
