name: Build and deploy to Prod

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-image:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build-image
    uses: ./.github/workflows/deploy.yml
    with:
      image_name: ${{ needs.build-image.outputs.image }}
      environment: prod
    secrets: inherit