name: Promote Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      new_tag:
        required: true
        type: string
    outputs:
      image:
        description: "Promoted image name"
        value: ${{ jobs.promote-image.outputs.image }}

jobs:
  promote-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.promote.outputs.image }}
    env:
      VERSION: ${{ inputs.new_tag }}
      IMAGE_NAME: ${{ inputs.image_name }}
      NEW_IMAGE: ghcr.io/${{ github.repository }}:${{ inputs.new_tag }}
    steps:
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Image
        run: docker pull $IMAGE_NAME

      - name: Tag Image
        id: promote
        run: |
          docker tag $IMAGE_NAME $NEW_IMAGE
          echo "image=$NEW_IMAGE" >> $GITHUB_OUTPUT

      - name: Push Promoted Image
        run: docker push $NEW_IMAGE
