name: Release

on:
    workflow_run:
        workflows: ["Build and deploy to UAT"]
        types:
        - completed
    push:
        branches:
        - release/*

permissions:
    contents: write
    packages: write
    id-token: write

jobs:
  extract-image-name:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.extract.outputs.image }}
    steps:
      - name: Extract short SHA
        id: short-sha
        run: echo "short-sha=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"

      - name: Extract Image Name
        id: extract
        run: echo "image=ghcr.io/${{ github.repository }}:${{ steps.short-sha.outputs.short-sha }}" >> $GITHUB_OUTPUT
  
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Extract Version
        id: extract
        run: echo "version=${GITHUB_REF_NAME#release/}" >> $GITHUB_OUTPUT

  promote-image:
    needs: [extract-image-name, extract-version]
    uses: ./.github/workflows/promote-image.yml
    with:
      image_name: ${{ needs.extract-image-name.outputs.image }}
      new_tag: ${{ jobs.extract-version.outputs.version }}

  tag-release:
    runs-on: ubuntu-latest
    needs: promote-image
    steps:
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create Git Tag
        run: |
            git tag ${{ needs.extract-version.outputs.version }} ${{ github.sha }}
            git push origin ${{ needs.extract-version.outputs.version }}

